#############################################################################
# Makefile for building: cgems
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  cgems.pro
# Template: app
# Command: /home/nichenko_s/anaconda3/bin/qmake -o Makefile cgems.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DIPMGEMPLUGIN -DNOPARTICLEARRAY -D__unix
CFLAGS        = -pipe -g -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wall -Wno-unused -g -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../standalone/GEMS3K -I../../../anaconda3/mkspecs/linux-g++
QMAKE         = /home/nichenko_s/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/nichenko_s/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/nichenko_s/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cgems3.1.0
DISTDIR = /home/nichenko_s/Development/gitGEMS3/gems3mel/obj/cgems3.1.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/reader.cpp \
		src/formulaparser.cpp \
		src/vector.cpp \
		src/cgems.cpp \
		src/physics.cpp \
		../standalone/GEMS3K/gdatastream.cpp \
		../standalone/GEMS3K/num_methods.cpp \
		../standalone/GEMS3K/s_solmod.cpp \
		../standalone/GEMS3K/s_solmod2.cpp \
		../standalone/GEMS3K/s_solmod3.cpp \
		../standalone/GEMS3K/s_solmod4.cpp \
		../standalone/GEMS3K/s_solmod5.cpp \
		../standalone/GEMS3K/s_solmod6.cpp \
		../standalone/GEMS3K/s_sorpmod.cpp \
		../standalone/GEMS3K/s_kinmet.cpp \
		../standalone/GEMS3K/ipm_chemical.cpp \
		../standalone/GEMS3K/ipm_chemical2.cpp \
		../standalone/GEMS3K/ipm_chemical3.cpp \
		../standalone/GEMS3K/ipm_chemical4.cpp \
		../standalone/GEMS3K/ipm_main.cpp \
		../standalone/GEMS3K/ipm_simplex.cpp \
		../standalone/GEMS3K/node.cpp \
		../standalone/GEMS3K/nodearray.cpp \
		../standalone/GEMS3K/node_format.cpp \
		../standalone/GEMS3K/ms_multi_file.cpp \
		../standalone/GEMS3K/ms_multi_format.cpp \
		../standalone/GEMS3K/ms_param.cpp \
		../standalone/GEMS3K/io_arrays.cpp \
		../standalone/GEMS3K/node_copy.cpp \
		../standalone/GEMS3K/ms_multi_copy.cpp \
		../standalone/GEMS3K/node_activities.cpp \
		../standalone/GEMS3K/node_kinetics.cpp \
		../standalone/GEMS3K/s_activity.cpp \
		../standalone/GEMS3K/s_activity2.cpp \
		../standalone/GEMS3K/s_activity3.cpp 
OBJECTS       = obj/main.o \
		obj/reader.o \
		obj/formulaparser.o \
		obj/vector.o \
		obj/cgems.o \
		obj/physics.o \
		obj/gdatastream.o \
		obj/num_methods.o \
		obj/s_solmod.o \
		obj/s_solmod2.o \
		obj/s_solmod3.o \
		obj/s_solmod4.o \
		obj/s_solmod5.o \
		obj/s_solmod6.o \
		obj/s_sorpmod.o \
		obj/s_kinmet.o \
		obj/ipm_chemical.o \
		obj/ipm_chemical2.o \
		obj/ipm_chemical3.o \
		obj/ipm_chemical4.o \
		obj/ipm_main.o \
		obj/ipm_simplex.o \
		obj/node.o \
		obj/nodearray.o \
		obj/node_format.o \
		obj/ms_multi_file.o \
		obj/ms_multi_format.o \
		obj/ms_param.o \
		obj/io_arrays.o \
		obj/node_copy.o \
		obj/ms_multi_copy.o \
		obj/node_activities.o \
		obj/node_kinetics.o \
		obj/s_activity.o \
		obj/s_activity2.o \
		obj/s_activity3.o
DIST          = ../../../anaconda3/mkspecs/features/spec_pre.prf \
		../../../anaconda3/mkspecs/common/unix.conf \
		../../../anaconda3/mkspecs/common/linux.conf \
		../../../anaconda3/mkspecs/common/sanitize.conf \
		../../../anaconda3/mkspecs/common/gcc-base.conf \
		../../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../../anaconda3/mkspecs/common/g++-base.conf \
		../../../anaconda3/mkspecs/common/g++-unix.conf \
		../../../anaconda3/mkspecs/qconfig.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda3/mkspecs/features/qt_functions.prf \
		../../../anaconda3/mkspecs/features/qt_config.prf \
		../../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../../anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../../anaconda3/mkspecs/features/toolchain.prf \
		../../../anaconda3/mkspecs/features/default_pre.prf \
		../standalone/GEMS3K/gems3k.pri \
		../../../anaconda3/mkspecs/features/resolve_config.prf \
		../../../anaconda3/mkspecs/features/default_post.prf \
		../../../anaconda3/mkspecs/features/qmake_use.prf \
		../../../anaconda3/mkspecs/features/file_copies.prf \
		../../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../../anaconda3/mkspecs/features/exceptions.prf \
		../../../anaconda3/mkspecs/features/yacc.prf \
		../../../anaconda3/mkspecs/features/lex.prf \
		cgems.pro src/reader.h \
		src/datatypes.h \
		src/formulaparser.h \
		src/vector.h \
		src/cgems.h \
		src/physics.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/tnt_i_refvec.h \
		../standalone/GEMS3K/tnt_array1d.h \
		../standalone/GEMS3K/tnt_array2d.h \
		../standalone/GEMS3K/tnt.h \
		../standalone/GEMS3K/jama_cholesky.h \
		../standalone/GEMS3K/jama_lu.h \
		../standalone/GEMS3K/num_methods.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/nodearray.h \
		../standalone/GEMS3K/io_arrays.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h src/main.cpp \
		src/reader.cpp \
		src/formulaparser.cpp \
		src/vector.cpp \
		src/cgems.cpp \
		src/physics.cpp \
		../standalone/GEMS3K/gdatastream.cpp \
		../standalone/GEMS3K/num_methods.cpp \
		../standalone/GEMS3K/s_solmod.cpp \
		../standalone/GEMS3K/s_solmod2.cpp \
		../standalone/GEMS3K/s_solmod3.cpp \
		../standalone/GEMS3K/s_solmod4.cpp \
		../standalone/GEMS3K/s_solmod5.cpp \
		../standalone/GEMS3K/s_solmod6.cpp \
		../standalone/GEMS3K/s_sorpmod.cpp \
		../standalone/GEMS3K/s_kinmet.cpp \
		../standalone/GEMS3K/ipm_chemical.cpp \
		../standalone/GEMS3K/ipm_chemical2.cpp \
		../standalone/GEMS3K/ipm_chemical3.cpp \
		../standalone/GEMS3K/ipm_chemical4.cpp \
		../standalone/GEMS3K/ipm_main.cpp \
		../standalone/GEMS3K/ipm_simplex.cpp \
		../standalone/GEMS3K/node.cpp \
		../standalone/GEMS3K/nodearray.cpp \
		../standalone/GEMS3K/node_format.cpp \
		../standalone/GEMS3K/ms_multi_file.cpp \
		../standalone/GEMS3K/ms_multi_format.cpp \
		../standalone/GEMS3K/ms_param.cpp \
		../standalone/GEMS3K/io_arrays.cpp \
		../standalone/GEMS3K/node_copy.cpp \
		../standalone/GEMS3K/ms_multi_copy.cpp \
		../standalone/GEMS3K/node_activities.cpp \
		../standalone/GEMS3K/node_kinetics.cpp \
		../standalone/GEMS3K/s_activity.cpp \
		../standalone/GEMS3K/s_activity2.cpp \
		../standalone/GEMS3K/s_activity3.cpp
QMAKE_TARGET  = release/cgems
DESTDIR       = 
TARGET        = release/cgems


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cgems.pro ../../../anaconda3/mkspecs/linux-g++/qmake.conf ../../../anaconda3/mkspecs/features/spec_pre.prf \
		../../../anaconda3/mkspecs/common/unix.conf \
		../../../anaconda3/mkspecs/common/linux.conf \
		../../../anaconda3/mkspecs/common/sanitize.conf \
		../../../anaconda3/mkspecs/common/gcc-base.conf \
		../../../anaconda3/mkspecs/common/gcc-base-unix.conf \
		../../../anaconda3/mkspecs/common/g++-base.conf \
		../../../anaconda3/mkspecs/common/g++-unix.conf \
		../../../anaconda3/mkspecs/qconfig.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda3/mkspecs/features/qt_functions.prf \
		../../../anaconda3/mkspecs/features/qt_config.prf \
		../../../anaconda3/mkspecs/linux-g++/qmake.conf \
		../../../anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../anaconda3/mkspecs/features/exclusive_builds.prf \
		../../../anaconda3/mkspecs/features/toolchain.prf \
		../../../anaconda3/mkspecs/features/default_pre.prf \
		../standalone/GEMS3K/gems3k.pri \
		../../../anaconda3/mkspecs/features/resolve_config.prf \
		../../../anaconda3/mkspecs/features/default_post.prf \
		../../../anaconda3/mkspecs/features/qmake_use.prf \
		../../../anaconda3/mkspecs/features/file_copies.prf \
		../../../anaconda3/mkspecs/features/testcase_targets.prf \
		../../../anaconda3/mkspecs/features/exceptions.prf \
		../../../anaconda3/mkspecs/features/yacc.prf \
		../../../anaconda3/mkspecs/features/lex.prf \
		cgems.pro
	$(QMAKE) -o Makefile cgems.pro
../../../anaconda3/mkspecs/features/spec_pre.prf:
../../../anaconda3/mkspecs/common/unix.conf:
../../../anaconda3/mkspecs/common/linux.conf:
../../../anaconda3/mkspecs/common/sanitize.conf:
../../../anaconda3/mkspecs/common/gcc-base.conf:
../../../anaconda3/mkspecs/common/gcc-base-unix.conf:
../../../anaconda3/mkspecs/common/g++-base.conf:
../../../anaconda3/mkspecs/common/g++-unix.conf:
../../../anaconda3/mkspecs/qconfig.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3drender.pri:
../../../anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_charts.pri:
../../../anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
../../../anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_core.pri:
../../../anaconda3/mkspecs/modules/qt_lib_core_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
../../../anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_dbus.pri:
../../../anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designer.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gui.pri:
../../../anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_help.pri:
../../../anaconda3/mkspecs/modules/qt_lib_help_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_location.pri:
../../../anaconda3/mkspecs/modules/qt_lib_location_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_network.pri:
../../../anaconda3/mkspecs/modules/qt_lib_network_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
../../../anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_nfc.pri:
../../../anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_opengl.pri:
../../../anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
../../../anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioning.pri:
../../../anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
../../../anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_repparser.pri:
../../../anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_script.pri:
../../../anaconda3/mkspecs/modules/qt_lib_script_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scxml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sensors.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialport.pri:
../../../anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sql.pri:
../../../anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_svg.pri:
../../../anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_testlib.pri:
../../../anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
../../../anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uitools.pri:
../../../anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webengine.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_websockets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webview.pri:
../../../anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_widgets.pri:
../../../anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
../../../anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xml.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../anaconda3/mkspecs/features/qt_functions.prf:
../../../anaconda3/mkspecs/features/qt_config.prf:
../../../anaconda3/mkspecs/linux-g++/qmake.conf:
../../../anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../anaconda3/mkspecs/features/exclusive_builds.prf:
../../../anaconda3/mkspecs/features/toolchain.prf:
../../../anaconda3/mkspecs/features/default_pre.prf:
../standalone/GEMS3K/gems3k.pri:
../../../anaconda3/mkspecs/features/resolve_config.prf:
../../../anaconda3/mkspecs/features/default_post.prf:
../../../anaconda3/mkspecs/features/qmake_use.prf:
../../../anaconda3/mkspecs/features/file_copies.prf:
../../../anaconda3/mkspecs/features/testcase_targets.prf:
../../../anaconda3/mkspecs/features/exceptions.prf:
../../../anaconda3/mkspecs/features/yacc.prf:
../../../anaconda3/mkspecs/features/lex.prf:
cgems.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile cgems.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/main.o: src/main.cpp src/cgems.h \
		src/reader.h \
		src/datatypes.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		src/formulaparser.h \
		src/physics.h \
		src/eigen/Core \
		src/eigen/src/Core/util/DisableStupidWarnings.h \
		src/eigen/src/Core/util/Macros.h \
		src/eigen/src/Core/util/MKL_support.h \
		src/eigen/src/misc/blas.h \
		src/eigen/src/Core/util/Constants.h \
		src/eigen/src/Core/util/Meta.h \
		src/eigen/src/Core/util/ForwardDeclarations.h \
		src/eigen/src/Core/util/StaticAssert.h \
		src/eigen/src/Core/util/XprHelper.h \
		src/eigen/src/Core/util/Memory.h \
		src/eigen/src/Core/NumTraits.h \
		src/eigen/src/Core/MathFunctions.h \
		src/eigen/src/Core/GenericPacketMath.h \
		src/eigen/src/Core/MathFunctionsImpl.h \
		src/eigen/src/Core/arch/Default/ConjHelper.h \
		src/eigen/src/Core/arch/SSE/PacketMath.h \
		src/eigen/src/Core/arch/AVX/PacketMath.h \
		src/eigen/src/Core/arch/AVX512/PacketMath.h \
		src/eigen/src/Core/arch/AVX512/MathFunctions.h \
		src/eigen/src/Core/arch/SSE/Complex.h \
		src/eigen/src/Core/arch/SSE/MathFunctions.h \
		src/eigen/src/Core/arch/AVX/MathFunctions.h \
		src/eigen/src/Core/arch/AVX/Complex.h \
		src/eigen/src/Core/arch/AVX/TypeCasting.h \
		src/eigen/src/Core/arch/SSE/TypeCasting.h \
		src/eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/eigen/src/Core/arch/AltiVec/MathFunctions.h \
		src/eigen/src/Core/arch/AltiVec/Complex.h \
		src/eigen/src/Core/arch/NEON/PacketMath.h \
		src/eigen/src/Core/arch/NEON/MathFunctions.h \
		src/eigen/src/Core/arch/NEON/Complex.h \
		src/eigen/src/Core/arch/ZVector/PacketMath.h \
		src/eigen/src/Core/arch/ZVector/MathFunctions.h \
		src/eigen/src/Core/arch/ZVector/Complex.h \
		src/eigen/src/Core/arch/CUDA/Half.h \
		src/eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		src/eigen/src/Core/arch/CUDA/TypeCasting.h \
		src/eigen/src/Core/arch/CUDA/PacketMath.h \
		src/eigen/src/Core/arch/CUDA/MathFunctions.h \
		src/eigen/src/Core/arch/Default/Settings.h \
		src/eigen/src/Core/functors/TernaryFunctors.h \
		src/eigen/src/Core/functors/BinaryFunctors.h \
		src/eigen/src/Core/functors/UnaryFunctors.h \
		src/eigen/src/Core/functors/NullaryFunctors.h \
		src/eigen/src/Core/functors/StlFunctors.h \
		src/eigen/src/Core/functors/AssignmentFunctors.h \
		src/eigen/src/Core/arch/CUDA/Complex.h \
		src/eigen/src/Core/IO.h \
		src/eigen/src/Core/DenseCoeffsBase.h \
		src/eigen/src/Core/DenseBase.h \
		src/eigen/src/plugins/BlockMethods.h \
		src/eigen/src/Core/MatrixBase.h \
		src/eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/eigen/src/Core/EigenBase.h \
		src/eigen/src/Core/Product.h \
		src/eigen/src/Core/CoreEvaluators.h \
		src/eigen/src/Core/AssignEvaluator.h \
		src/eigen/src/Core/Assign.h \
		src/eigen/src/Core/ArrayBase.h \
		src/eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/eigen/src/Core/util/BlasUtil.h \
		src/eigen/src/Core/DenseStorage.h \
		src/eigen/src/Core/NestByValue.h \
		src/eigen/src/Core/ReturnByValue.h \
		src/eigen/src/Core/NoAlias.h \
		src/eigen/src/Core/PlainObjectBase.h \
		src/eigen/src/Core/Matrix.h \
		src/eigen/src/Core/Array.h \
		src/eigen/src/Core/CwiseTernaryOp.h \
		src/eigen/src/Core/CwiseBinaryOp.h \
		src/eigen/src/Core/CwiseUnaryOp.h \
		src/eigen/src/Core/CwiseNullaryOp.h \
		src/eigen/src/Core/CwiseUnaryView.h \
		src/eigen/src/Core/SelfCwiseBinaryOp.h \
		src/eigen/src/Core/Dot.h \
		src/eigen/src/Core/StableNorm.h \
		src/eigen/src/Core/Stride.h \
		src/eigen/src/Core/MapBase.h \
		src/eigen/src/Core/Map.h \
		src/eigen/src/Core/Ref.h \
		src/eigen/src/Core/Block.h \
		src/eigen/src/Core/VectorBlock.h \
		src/eigen/src/Core/Transpose.h \
		src/eigen/src/Core/DiagonalMatrix.h \
		src/eigen/src/Core/Diagonal.h \
		src/eigen/src/Core/DiagonalProduct.h \
		src/eigen/src/Core/Redux.h \
		src/eigen/src/Core/Visitor.h \
		src/eigen/src/Core/Fuzzy.h \
		src/eigen/src/Core/Swap.h \
		src/eigen/src/Core/CommaInitializer.h \
		src/eigen/src/Core/GeneralProduct.h \
		src/eigen/src/Core/Solve.h \
		src/eigen/src/Core/Inverse.h \
		src/eigen/src/Core/SolverBase.h \
		src/eigen/src/Core/PermutationMatrix.h \
		src/eigen/src/Core/Transpositions.h \
		src/eigen/src/Core/TriangularMatrix.h \
		src/eigen/src/Core/SelfAdjointView.h \
		src/eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/eigen/src/Core/products/Parallelizer.h \
		src/eigen/src/Core/ProductEvaluators.h \
		src/eigen/src/Core/products/GeneralMatrixVector.h \
		src/eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/eigen/src/Core/SolveTriangular.h \
		src/eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/eigen/src/Core/products/SelfadjointProduct.h \
		src/eigen/src/Core/products/SelfadjointRank2Update.h \
		src/eigen/src/Core/products/TriangularMatrixVector.h \
		src/eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/eigen/src/Core/products/TriangularSolverMatrix.h \
		src/eigen/src/Core/products/TriangularSolverVector.h \
		src/eigen/src/Core/BandMatrix.h \
		src/eigen/src/Core/CoreIterators.h \
		src/eigen/src/Core/ConditionEstimator.h \
		src/eigen/src/Core/BooleanRedux.h \
		src/eigen/src/Core/Select.h \
		src/eigen/src/Core/VectorwiseOp.h \
		src/eigen/src/Core/Random.h \
		src/eigen/src/Core/Replicate.h \
		src/eigen/src/Core/Reverse.h \
		src/eigen/src/Core/ArrayWrapper.h \
		src/eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		src/eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		src/eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		src/eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		src/eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		src/eigen/src/Core/Assign_MKL.h \
		src/eigen/src/Core/GlobalFunctions.h \
		src/eigen/src/Core/util/ReenableStupidWarnings.h \
		src/eigen/Dense \
		src/eigen/LU \
		src/eigen/src/misc/Kernel.h \
		src/eigen/src/misc/Image.h \
		src/eigen/src/LU/FullPivLU.h \
		src/eigen/src/LU/PartialPivLU.h \
		src/eigen/src/misc/lapacke.h \
		src/eigen/src/misc/lapacke_mangling.h \
		src/eigen/src/LU/PartialPivLU_LAPACKE.h \
		src/eigen/src/LU/Determinant.h \
		src/eigen/src/LU/InverseImpl.h \
		src/eigen/src/LU/arch/Inverse_SSE.h \
		src/eigen/Cholesky \
		src/eigen/Jacobi \
		src/eigen/src/Jacobi/Jacobi.h \
		src/eigen/src/Cholesky/LLT.h \
		src/eigen/src/Cholesky/LDLT.h \
		src/eigen/src/Cholesky/LLT_LAPACKE.h \
		src/eigen/QR \
		src/eigen/Householder \
		src/eigen/src/Householder/Householder.h \
		src/eigen/src/Householder/HouseholderSequence.h \
		src/eigen/src/Householder/BlockHouseholder.h \
		src/eigen/src/QR/HouseholderQR.h \
		src/eigen/src/QR/FullPivHouseholderQR.h \
		src/eigen/src/QR/ColPivHouseholderQR.h \
		src/eigen/src/QR/CompleteOrthogonalDecomposition.h \
		src/eigen/src/QR/HouseholderQR_LAPACKE.h \
		src/eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		src/eigen/SVD \
		src/eigen/src/misc/RealSvd2x2.h \
		src/eigen/src/SVD/UpperBidiagonalization.h \
		src/eigen/src/SVD/SVDBase.h \
		src/eigen/src/SVD/JacobiSVD.h \
		src/eigen/src/SVD/BDCSVD.h \
		src/eigen/src/SVD/JacobiSVD_LAPACKE.h \
		src/eigen/Geometry \
		src/eigen/src/Geometry/OrthoMethods.h \
		src/eigen/src/Geometry/EulerAngles.h \
		src/eigen/src/Geometry/Homogeneous.h \
		src/eigen/src/Geometry/RotationBase.h \
		src/eigen/src/Geometry/Rotation2D.h \
		src/eigen/src/Geometry/Quaternion.h \
		src/eigen/src/Geometry/AngleAxis.h \
		src/eigen/src/Geometry/Transform.h \
		src/eigen/src/Geometry/Translation.h \
		src/eigen/src/Geometry/Scaling.h \
		src/eigen/src/Geometry/Hyperplane.h \
		src/eigen/src/Geometry/ParametrizedLine.h \
		src/eigen/src/Geometry/AlignedBox.h \
		src/eigen/src/Geometry/Umeyama.h \
		src/eigen/src/Geometry/arch/Geometry_SSE.h \
		src/eigen/Eigenvalues \
		src/eigen/src/Eigenvalues/Tridiagonalization.h \
		src/eigen/src/Eigenvalues/RealSchur.h \
		src/eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/eigen/src/Eigenvalues/EigenSolver.h \
		src/eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/eigen/src/Eigenvalues/ComplexSchur.h \
		src/eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/eigen/src/Eigenvalues/RealQZ.h \
		src/eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		src/eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		src/eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/reader.o: src/reader.cpp src/reader.h \
		src/datatypes.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		src/formulaparser.h \
		src/physics.h \
		src/eigen/Core \
		src/eigen/src/Core/util/DisableStupidWarnings.h \
		src/eigen/src/Core/util/Macros.h \
		src/eigen/src/Core/util/MKL_support.h \
		src/eigen/src/misc/blas.h \
		src/eigen/src/Core/util/Constants.h \
		src/eigen/src/Core/util/Meta.h \
		src/eigen/src/Core/util/ForwardDeclarations.h \
		src/eigen/src/Core/util/StaticAssert.h \
		src/eigen/src/Core/util/XprHelper.h \
		src/eigen/src/Core/util/Memory.h \
		src/eigen/src/Core/NumTraits.h \
		src/eigen/src/Core/MathFunctions.h \
		src/eigen/src/Core/GenericPacketMath.h \
		src/eigen/src/Core/MathFunctionsImpl.h \
		src/eigen/src/Core/arch/Default/ConjHelper.h \
		src/eigen/src/Core/arch/SSE/PacketMath.h \
		src/eigen/src/Core/arch/AVX/PacketMath.h \
		src/eigen/src/Core/arch/AVX512/PacketMath.h \
		src/eigen/src/Core/arch/AVX512/MathFunctions.h \
		src/eigen/src/Core/arch/SSE/Complex.h \
		src/eigen/src/Core/arch/SSE/MathFunctions.h \
		src/eigen/src/Core/arch/AVX/MathFunctions.h \
		src/eigen/src/Core/arch/AVX/Complex.h \
		src/eigen/src/Core/arch/AVX/TypeCasting.h \
		src/eigen/src/Core/arch/SSE/TypeCasting.h \
		src/eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/eigen/src/Core/arch/AltiVec/MathFunctions.h \
		src/eigen/src/Core/arch/AltiVec/Complex.h \
		src/eigen/src/Core/arch/NEON/PacketMath.h \
		src/eigen/src/Core/arch/NEON/MathFunctions.h \
		src/eigen/src/Core/arch/NEON/Complex.h \
		src/eigen/src/Core/arch/ZVector/PacketMath.h \
		src/eigen/src/Core/arch/ZVector/MathFunctions.h \
		src/eigen/src/Core/arch/ZVector/Complex.h \
		src/eigen/src/Core/arch/CUDA/Half.h \
		src/eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		src/eigen/src/Core/arch/CUDA/TypeCasting.h \
		src/eigen/src/Core/arch/CUDA/PacketMath.h \
		src/eigen/src/Core/arch/CUDA/MathFunctions.h \
		src/eigen/src/Core/arch/Default/Settings.h \
		src/eigen/src/Core/functors/TernaryFunctors.h \
		src/eigen/src/Core/functors/BinaryFunctors.h \
		src/eigen/src/Core/functors/UnaryFunctors.h \
		src/eigen/src/Core/functors/NullaryFunctors.h \
		src/eigen/src/Core/functors/StlFunctors.h \
		src/eigen/src/Core/functors/AssignmentFunctors.h \
		src/eigen/src/Core/arch/CUDA/Complex.h \
		src/eigen/src/Core/IO.h \
		src/eigen/src/Core/DenseCoeffsBase.h \
		src/eigen/src/Core/DenseBase.h \
		src/eigen/src/plugins/BlockMethods.h \
		src/eigen/src/Core/MatrixBase.h \
		src/eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/eigen/src/Core/EigenBase.h \
		src/eigen/src/Core/Product.h \
		src/eigen/src/Core/CoreEvaluators.h \
		src/eigen/src/Core/AssignEvaluator.h \
		src/eigen/src/Core/Assign.h \
		src/eigen/src/Core/ArrayBase.h \
		src/eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/eigen/src/Core/util/BlasUtil.h \
		src/eigen/src/Core/DenseStorage.h \
		src/eigen/src/Core/NestByValue.h \
		src/eigen/src/Core/ReturnByValue.h \
		src/eigen/src/Core/NoAlias.h \
		src/eigen/src/Core/PlainObjectBase.h \
		src/eigen/src/Core/Matrix.h \
		src/eigen/src/Core/Array.h \
		src/eigen/src/Core/CwiseTernaryOp.h \
		src/eigen/src/Core/CwiseBinaryOp.h \
		src/eigen/src/Core/CwiseUnaryOp.h \
		src/eigen/src/Core/CwiseNullaryOp.h \
		src/eigen/src/Core/CwiseUnaryView.h \
		src/eigen/src/Core/SelfCwiseBinaryOp.h \
		src/eigen/src/Core/Dot.h \
		src/eigen/src/Core/StableNorm.h \
		src/eigen/src/Core/Stride.h \
		src/eigen/src/Core/MapBase.h \
		src/eigen/src/Core/Map.h \
		src/eigen/src/Core/Ref.h \
		src/eigen/src/Core/Block.h \
		src/eigen/src/Core/VectorBlock.h \
		src/eigen/src/Core/Transpose.h \
		src/eigen/src/Core/DiagonalMatrix.h \
		src/eigen/src/Core/Diagonal.h \
		src/eigen/src/Core/DiagonalProduct.h \
		src/eigen/src/Core/Redux.h \
		src/eigen/src/Core/Visitor.h \
		src/eigen/src/Core/Fuzzy.h \
		src/eigen/src/Core/Swap.h \
		src/eigen/src/Core/CommaInitializer.h \
		src/eigen/src/Core/GeneralProduct.h \
		src/eigen/src/Core/Solve.h \
		src/eigen/src/Core/Inverse.h \
		src/eigen/src/Core/SolverBase.h \
		src/eigen/src/Core/PermutationMatrix.h \
		src/eigen/src/Core/Transpositions.h \
		src/eigen/src/Core/TriangularMatrix.h \
		src/eigen/src/Core/SelfAdjointView.h \
		src/eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/eigen/src/Core/products/Parallelizer.h \
		src/eigen/src/Core/ProductEvaluators.h \
		src/eigen/src/Core/products/GeneralMatrixVector.h \
		src/eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/eigen/src/Core/SolveTriangular.h \
		src/eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/eigen/src/Core/products/SelfadjointProduct.h \
		src/eigen/src/Core/products/SelfadjointRank2Update.h \
		src/eigen/src/Core/products/TriangularMatrixVector.h \
		src/eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/eigen/src/Core/products/TriangularSolverMatrix.h \
		src/eigen/src/Core/products/TriangularSolverVector.h \
		src/eigen/src/Core/BandMatrix.h \
		src/eigen/src/Core/CoreIterators.h \
		src/eigen/src/Core/ConditionEstimator.h \
		src/eigen/src/Core/BooleanRedux.h \
		src/eigen/src/Core/Select.h \
		src/eigen/src/Core/VectorwiseOp.h \
		src/eigen/src/Core/Random.h \
		src/eigen/src/Core/Replicate.h \
		src/eigen/src/Core/Reverse.h \
		src/eigen/src/Core/ArrayWrapper.h \
		src/eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		src/eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		src/eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		src/eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		src/eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		src/eigen/src/Core/Assign_MKL.h \
		src/eigen/src/Core/GlobalFunctions.h \
		src/eigen/src/Core/util/ReenableStupidWarnings.h \
		src/eigen/Dense \
		src/eigen/LU \
		src/eigen/src/misc/Kernel.h \
		src/eigen/src/misc/Image.h \
		src/eigen/src/LU/FullPivLU.h \
		src/eigen/src/LU/PartialPivLU.h \
		src/eigen/src/misc/lapacke.h \
		src/eigen/src/misc/lapacke_mangling.h \
		src/eigen/src/LU/PartialPivLU_LAPACKE.h \
		src/eigen/src/LU/Determinant.h \
		src/eigen/src/LU/InverseImpl.h \
		src/eigen/src/LU/arch/Inverse_SSE.h \
		src/eigen/Cholesky \
		src/eigen/Jacobi \
		src/eigen/src/Jacobi/Jacobi.h \
		src/eigen/src/Cholesky/LLT.h \
		src/eigen/src/Cholesky/LDLT.h \
		src/eigen/src/Cholesky/LLT_LAPACKE.h \
		src/eigen/QR \
		src/eigen/Householder \
		src/eigen/src/Householder/Householder.h \
		src/eigen/src/Householder/HouseholderSequence.h \
		src/eigen/src/Householder/BlockHouseholder.h \
		src/eigen/src/QR/HouseholderQR.h \
		src/eigen/src/QR/FullPivHouseholderQR.h \
		src/eigen/src/QR/ColPivHouseholderQR.h \
		src/eigen/src/QR/CompleteOrthogonalDecomposition.h \
		src/eigen/src/QR/HouseholderQR_LAPACKE.h \
		src/eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		src/eigen/SVD \
		src/eigen/src/misc/RealSvd2x2.h \
		src/eigen/src/SVD/UpperBidiagonalization.h \
		src/eigen/src/SVD/SVDBase.h \
		src/eigen/src/SVD/JacobiSVD.h \
		src/eigen/src/SVD/BDCSVD.h \
		src/eigen/src/SVD/JacobiSVD_LAPACKE.h \
		src/eigen/Geometry \
		src/eigen/src/Geometry/OrthoMethods.h \
		src/eigen/src/Geometry/EulerAngles.h \
		src/eigen/src/Geometry/Homogeneous.h \
		src/eigen/src/Geometry/RotationBase.h \
		src/eigen/src/Geometry/Rotation2D.h \
		src/eigen/src/Geometry/Quaternion.h \
		src/eigen/src/Geometry/AngleAxis.h \
		src/eigen/src/Geometry/Transform.h \
		src/eigen/src/Geometry/Translation.h \
		src/eigen/src/Geometry/Scaling.h \
		src/eigen/src/Geometry/Hyperplane.h \
		src/eigen/src/Geometry/ParametrizedLine.h \
		src/eigen/src/Geometry/AlignedBox.h \
		src/eigen/src/Geometry/Umeyama.h \
		src/eigen/src/Geometry/arch/Geometry_SSE.h \
		src/eigen/Eigenvalues \
		src/eigen/src/Eigenvalues/Tridiagonalization.h \
		src/eigen/src/Eigenvalues/RealSchur.h \
		src/eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/eigen/src/Eigenvalues/EigenSolver.h \
		src/eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/eigen/src/Eigenvalues/ComplexSchur.h \
		src/eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/eigen/src/Eigenvalues/RealQZ.h \
		src/eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		src/eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		src/eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
		src/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/reader.o src/reader.cpp

obj/formulaparser.o: src/formulaparser.cpp src/formulaparser.h \
		src/datatypes.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/formulaparser.o src/formulaparser.cpp

obj/vector.o: src/vector.cpp src/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/vector.o src/vector.cpp

obj/cgems.o: src/cgems.cpp src/cgems.h \
		src/reader.h \
		src/datatypes.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		src/formulaparser.h \
		src/physics.h \
		src/eigen/Core \
		src/eigen/src/Core/util/DisableStupidWarnings.h \
		src/eigen/src/Core/util/Macros.h \
		src/eigen/src/Core/util/MKL_support.h \
		src/eigen/src/misc/blas.h \
		src/eigen/src/Core/util/Constants.h \
		src/eigen/src/Core/util/Meta.h \
		src/eigen/src/Core/util/ForwardDeclarations.h \
		src/eigen/src/Core/util/StaticAssert.h \
		src/eigen/src/Core/util/XprHelper.h \
		src/eigen/src/Core/util/Memory.h \
		src/eigen/src/Core/NumTraits.h \
		src/eigen/src/Core/MathFunctions.h \
		src/eigen/src/Core/GenericPacketMath.h \
		src/eigen/src/Core/MathFunctionsImpl.h \
		src/eigen/src/Core/arch/Default/ConjHelper.h \
		src/eigen/src/Core/arch/SSE/PacketMath.h \
		src/eigen/src/Core/arch/AVX/PacketMath.h \
		src/eigen/src/Core/arch/AVX512/PacketMath.h \
		src/eigen/src/Core/arch/AVX512/MathFunctions.h \
		src/eigen/src/Core/arch/SSE/Complex.h \
		src/eigen/src/Core/arch/SSE/MathFunctions.h \
		src/eigen/src/Core/arch/AVX/MathFunctions.h \
		src/eigen/src/Core/arch/AVX/Complex.h \
		src/eigen/src/Core/arch/AVX/TypeCasting.h \
		src/eigen/src/Core/arch/SSE/TypeCasting.h \
		src/eigen/src/Core/arch/AltiVec/PacketMath.h \
		src/eigen/src/Core/arch/AltiVec/MathFunctions.h \
		src/eigen/src/Core/arch/AltiVec/Complex.h \
		src/eigen/src/Core/arch/NEON/PacketMath.h \
		src/eigen/src/Core/arch/NEON/MathFunctions.h \
		src/eigen/src/Core/arch/NEON/Complex.h \
		src/eigen/src/Core/arch/ZVector/PacketMath.h \
		src/eigen/src/Core/arch/ZVector/MathFunctions.h \
		src/eigen/src/Core/arch/ZVector/Complex.h \
		src/eigen/src/Core/arch/CUDA/Half.h \
		src/eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		src/eigen/src/Core/arch/CUDA/TypeCasting.h \
		src/eigen/src/Core/arch/CUDA/PacketMath.h \
		src/eigen/src/Core/arch/CUDA/MathFunctions.h \
		src/eigen/src/Core/arch/Default/Settings.h \
		src/eigen/src/Core/functors/TernaryFunctors.h \
		src/eigen/src/Core/functors/BinaryFunctors.h \
		src/eigen/src/Core/functors/UnaryFunctors.h \
		src/eigen/src/Core/functors/NullaryFunctors.h \
		src/eigen/src/Core/functors/StlFunctors.h \
		src/eigen/src/Core/functors/AssignmentFunctors.h \
		src/eigen/src/Core/arch/CUDA/Complex.h \
		src/eigen/src/Core/IO.h \
		src/eigen/src/Core/DenseCoeffsBase.h \
		src/eigen/src/Core/DenseBase.h \
		src/eigen/src/plugins/BlockMethods.h \
		src/eigen/src/Core/MatrixBase.h \
		src/eigen/src/plugins/CommonCwiseUnaryOps.h \
		src/eigen/src/plugins/CommonCwiseBinaryOps.h \
		src/eigen/src/plugins/MatrixCwiseUnaryOps.h \
		src/eigen/src/plugins/MatrixCwiseBinaryOps.h \
		src/eigen/src/Core/EigenBase.h \
		src/eigen/src/Core/Product.h \
		src/eigen/src/Core/CoreEvaluators.h \
		src/eigen/src/Core/AssignEvaluator.h \
		src/eigen/src/Core/Assign.h \
		src/eigen/src/Core/ArrayBase.h \
		src/eigen/src/plugins/ArrayCwiseUnaryOps.h \
		src/eigen/src/plugins/ArrayCwiseBinaryOps.h \
		src/eigen/src/Core/util/BlasUtil.h \
		src/eigen/src/Core/DenseStorage.h \
		src/eigen/src/Core/NestByValue.h \
		src/eigen/src/Core/ReturnByValue.h \
		src/eigen/src/Core/NoAlias.h \
		src/eigen/src/Core/PlainObjectBase.h \
		src/eigen/src/Core/Matrix.h \
		src/eigen/src/Core/Array.h \
		src/eigen/src/Core/CwiseTernaryOp.h \
		src/eigen/src/Core/CwiseBinaryOp.h \
		src/eigen/src/Core/CwiseUnaryOp.h \
		src/eigen/src/Core/CwiseNullaryOp.h \
		src/eigen/src/Core/CwiseUnaryView.h \
		src/eigen/src/Core/SelfCwiseBinaryOp.h \
		src/eigen/src/Core/Dot.h \
		src/eigen/src/Core/StableNorm.h \
		src/eigen/src/Core/Stride.h \
		src/eigen/src/Core/MapBase.h \
		src/eigen/src/Core/Map.h \
		src/eigen/src/Core/Ref.h \
		src/eigen/src/Core/Block.h \
		src/eigen/src/Core/VectorBlock.h \
		src/eigen/src/Core/Transpose.h \
		src/eigen/src/Core/DiagonalMatrix.h \
		src/eigen/src/Core/Diagonal.h \
		src/eigen/src/Core/DiagonalProduct.h \
		src/eigen/src/Core/Redux.h \
		src/eigen/src/Core/Visitor.h \
		src/eigen/src/Core/Fuzzy.h \
		src/eigen/src/Core/Swap.h \
		src/eigen/src/Core/CommaInitializer.h \
		src/eigen/src/Core/GeneralProduct.h \
		src/eigen/src/Core/Solve.h \
		src/eigen/src/Core/Inverse.h \
		src/eigen/src/Core/SolverBase.h \
		src/eigen/src/Core/PermutationMatrix.h \
		src/eigen/src/Core/Transpositions.h \
		src/eigen/src/Core/TriangularMatrix.h \
		src/eigen/src/Core/SelfAdjointView.h \
		src/eigen/src/Core/products/GeneralBlockPanelKernel.h \
		src/eigen/src/Core/products/Parallelizer.h \
		src/eigen/src/Core/ProductEvaluators.h \
		src/eigen/src/Core/products/GeneralMatrixVector.h \
		src/eigen/src/Core/products/GeneralMatrixMatrix.h \
		src/eigen/src/Core/SolveTriangular.h \
		src/eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		src/eigen/src/Core/products/SelfadjointMatrixVector.h \
		src/eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		src/eigen/src/Core/products/SelfadjointProduct.h \
		src/eigen/src/Core/products/SelfadjointRank2Update.h \
		src/eigen/src/Core/products/TriangularMatrixVector.h \
		src/eigen/src/Core/products/TriangularMatrixMatrix.h \
		src/eigen/src/Core/products/TriangularSolverMatrix.h \
		src/eigen/src/Core/products/TriangularSolverVector.h \
		src/eigen/src/Core/BandMatrix.h \
		src/eigen/src/Core/CoreIterators.h \
		src/eigen/src/Core/ConditionEstimator.h \
		src/eigen/src/Core/BooleanRedux.h \
		src/eigen/src/Core/Select.h \
		src/eigen/src/Core/VectorwiseOp.h \
		src/eigen/src/Core/Random.h \
		src/eigen/src/Core/Replicate.h \
		src/eigen/src/Core/Reverse.h \
		src/eigen/src/Core/ArrayWrapper.h \
		src/eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		src/eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		src/eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		src/eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		src/eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		src/eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		src/eigen/src/Core/Assign_MKL.h \
		src/eigen/src/Core/GlobalFunctions.h \
		src/eigen/src/Core/util/ReenableStupidWarnings.h \
		src/eigen/Dense \
		src/eigen/LU \
		src/eigen/src/misc/Kernel.h \
		src/eigen/src/misc/Image.h \
		src/eigen/src/LU/FullPivLU.h \
		src/eigen/src/LU/PartialPivLU.h \
		src/eigen/src/misc/lapacke.h \
		src/eigen/src/misc/lapacke_mangling.h \
		src/eigen/src/LU/PartialPivLU_LAPACKE.h \
		src/eigen/src/LU/Determinant.h \
		src/eigen/src/LU/InverseImpl.h \
		src/eigen/src/LU/arch/Inverse_SSE.h \
		src/eigen/Cholesky \
		src/eigen/Jacobi \
		src/eigen/src/Jacobi/Jacobi.h \
		src/eigen/src/Cholesky/LLT.h \
		src/eigen/src/Cholesky/LDLT.h \
		src/eigen/src/Cholesky/LLT_LAPACKE.h \
		src/eigen/QR \
		src/eigen/Householder \
		src/eigen/src/Householder/Householder.h \
		src/eigen/src/Householder/HouseholderSequence.h \
		src/eigen/src/Householder/BlockHouseholder.h \
		src/eigen/src/QR/HouseholderQR.h \
		src/eigen/src/QR/FullPivHouseholderQR.h \
		src/eigen/src/QR/ColPivHouseholderQR.h \
		src/eigen/src/QR/CompleteOrthogonalDecomposition.h \
		src/eigen/src/QR/HouseholderQR_LAPACKE.h \
		src/eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		src/eigen/SVD \
		src/eigen/src/misc/RealSvd2x2.h \
		src/eigen/src/SVD/UpperBidiagonalization.h \
		src/eigen/src/SVD/SVDBase.h \
		src/eigen/src/SVD/JacobiSVD.h \
		src/eigen/src/SVD/BDCSVD.h \
		src/eigen/src/SVD/JacobiSVD_LAPACKE.h \
		src/eigen/Geometry \
		src/eigen/src/Geometry/OrthoMethods.h \
		src/eigen/src/Geometry/EulerAngles.h \
		src/eigen/src/Geometry/Homogeneous.h \
		src/eigen/src/Geometry/RotationBase.h \
		src/eigen/src/Geometry/Rotation2D.h \
		src/eigen/src/Geometry/Quaternion.h \
		src/eigen/src/Geometry/AngleAxis.h \
		src/eigen/src/Geometry/Transform.h \
		src/eigen/src/Geometry/Translation.h \
		src/eigen/src/Geometry/Scaling.h \
		src/eigen/src/Geometry/Hyperplane.h \
		src/eigen/src/Geometry/ParametrizedLine.h \
		src/eigen/src/Geometry/AlignedBox.h \
		src/eigen/src/Geometry/Umeyama.h \
		src/eigen/src/Geometry/arch/Geometry_SSE.h \
		src/eigen/Eigenvalues \
		src/eigen/src/Eigenvalues/Tridiagonalization.h \
		src/eigen/src/Eigenvalues/RealSchur.h \
		src/eigen/src/Eigenvalues/HessenbergDecomposition.h \
		src/eigen/src/Eigenvalues/EigenSolver.h \
		src/eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		src/eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		src/eigen/src/Eigenvalues/ComplexSchur.h \
		src/eigen/src/Eigenvalues/ComplexEigenSolver.h \
		src/eigen/src/Eigenvalues/RealQZ.h \
		src/eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		src/eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		src/eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		src/eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		src/eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cgems.o src/cgems.cpp

obj/physics.o: src/physics.cpp src/physics.h \
		src/datatypes.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/physics.o src/physics.cpp

obj/gdatastream.o: ../standalone/GEMS3K/gdatastream.cpp ../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gdatastream.o ../standalone/GEMS3K/gdatastream.cpp

obj/num_methods.o: ../standalone/GEMS3K/num_methods.cpp ../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/num_methods.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/num_methods.o ../standalone/GEMS3K/num_methods.cpp

obj/s_solmod.o: ../standalone/GEMS3K/s_solmod.cpp ../standalone/GEMS3K/s_solmod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_solmod.o ../standalone/GEMS3K/s_solmod.cpp

obj/s_solmod2.o: ../standalone/GEMS3K/s_solmod2.cpp ../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/verror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_solmod2.o ../standalone/GEMS3K/s_solmod2.cpp

obj/s_solmod3.o: ../standalone/GEMS3K/s_solmod3.cpp ../standalone/GEMS3K/s_solmod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_solmod3.o ../standalone/GEMS3K/s_solmod3.cpp

obj/s_solmod4.o: ../standalone/GEMS3K/s_solmod4.cpp ../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/s_solmod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_solmod4.o ../standalone/GEMS3K/s_solmod4.cpp

obj/s_solmod5.o: ../standalone/GEMS3K/s_solmod5.cpp ../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/s_solmod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_solmod5.o ../standalone/GEMS3K/s_solmod5.cpp

obj/s_solmod6.o: ../standalone/GEMS3K/s_solmod6.cpp ../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/s_solmod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_solmod6.o ../standalone/GEMS3K/s_solmod6.cpp

obj/s_sorpmod.o: ../standalone/GEMS3K/s_sorpmod.cpp ../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/s_solmod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_sorpmod.o ../standalone/GEMS3K/s_sorpmod.cpp

obj/s_kinmet.o: ../standalone/GEMS3K/s_kinmet.cpp ../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_kinmet.o ../standalone/GEMS3K/s_kinmet.cpp

obj/ipm_chemical.o: ../standalone/GEMS3K/ipm_chemical.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ipm_chemical.o ../standalone/GEMS3K/ipm_chemical.cpp

obj/ipm_chemical2.o: ../standalone/GEMS3K/ipm_chemical2.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ipm_chemical2.o ../standalone/GEMS3K/ipm_chemical2.cpp

obj/ipm_chemical3.o: ../standalone/GEMS3K/ipm_chemical3.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ipm_chemical3.o ../standalone/GEMS3K/ipm_chemical3.cpp

obj/ipm_chemical4.o: ../standalone/GEMS3K/ipm_chemical4.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ipm_chemical4.o ../standalone/GEMS3K/ipm_chemical4.cpp

obj/ipm_main.o: ../standalone/GEMS3K/ipm_main.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		../standalone/GEMS3K/jama_lu.h \
		../standalone/GEMS3K/tnt.h \
		../standalone/GEMS3K/tnt_array1d.h \
		../standalone/GEMS3K/tnt_i_refvec.h \
		../standalone/GEMS3K/tnt_array2d.h \
		../standalone/GEMS3K/jama_cholesky.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ipm_main.o ../standalone/GEMS3K/ipm_main.cpp

obj/ipm_simplex.o: ../standalone/GEMS3K/ipm_simplex.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		../standalone/GEMS3K/num_methods.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ipm_simplex.o ../standalone/GEMS3K/ipm_simplex.cpp

obj/node.o: ../standalone/GEMS3K/node.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		../standalone/GEMS3K/num_methods.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/node.o ../standalone/GEMS3K/node.cpp

obj/nodearray.o: ../standalone/GEMS3K/nodearray.cpp ../standalone/GEMS3K/nodearray.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		../standalone/GEMS3K/io_arrays.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/nodearray.o ../standalone/GEMS3K/nodearray.cpp

obj/node_format.o: ../standalone/GEMS3K/node_format.cpp ../standalone/GEMS3K/io_arrays.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		../standalone/GEMS3K/nodearray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/node_format.o ../standalone/GEMS3K/node_format.cpp

obj/ms_multi_file.o: ../standalone/GEMS3K/ms_multi_file.cpp ../standalone/GEMS3K/io_arrays.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ms_multi_file.o ../standalone/GEMS3K/ms_multi_file.cpp

obj/ms_multi_format.o: ../standalone/GEMS3K/ms_multi_format.cpp ../standalone/GEMS3K/io_arrays.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ms_multi_format.o ../standalone/GEMS3K/ms_multi_format.cpp

obj/ms_param.o: ../standalone/GEMS3K/ms_param.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/num_methods.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ms_param.o ../standalone/GEMS3K/ms_param.cpp

obj/io_arrays.o: ../standalone/GEMS3K/io_arrays.cpp ../standalone/GEMS3K/io_arrays.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/v_user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/io_arrays.o ../standalone/GEMS3K/io_arrays.cpp

obj/node_copy.o: ../standalone/GEMS3K/node_copy.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h \
		../standalone/GEMS3K/num_methods.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/node_copy.o ../standalone/GEMS3K/node_copy.cpp

obj/ms_multi_copy.o: ../standalone/GEMS3K/ms_multi_copy.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ms_multi_copy.o ../standalone/GEMS3K/ms_multi_copy.cpp

obj/node_activities.o: ../standalone/GEMS3K/node_activities.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/node_activities.o ../standalone/GEMS3K/node_activities.cpp

obj/node_kinetics.o: ../standalone/GEMS3K/node_kinetics.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/node_kinetics.o ../standalone/GEMS3K/node_kinetics.cpp

obj/s_activity.o: ../standalone/GEMS3K/s_activity.cpp ../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_activity.o ../standalone/GEMS3K/s_activity.cpp

obj/s_activity2.o: ../standalone/GEMS3K/s_activity2.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_activity2.o ../standalone/GEMS3K/s_activity2.cpp

obj/s_activity3.o: ../standalone/GEMS3K/s_activity3.cpp ../standalone/GEMS3K/node.h \
		../standalone/GEMS3K/m_param.h \
		../standalone/GEMS3K/gdatastream.h \
		../standalone/GEMS3K/verror.h \
		../standalone/GEMS3K/ms_multi.h \
		../standalone/GEMS3K/m_const.h \
		../standalone/GEMS3K/v_user.h \
		../standalone/GEMS3K/datach.h \
		../standalone/GEMS3K/s_solmod.h \
		../standalone/GEMS3K/s_sorpmod.h \
		../standalone/GEMS3K/s_kinmet.h \
		../standalone/GEMS3K/databr.h \
		../standalone/GEMS3K/activities.h \
		../standalone/GEMS3K/kinetics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/s_activity3.o ../standalone/GEMS3K/s_activity3.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

